name: Build Image

on:
  push:
    branches: [ master ]

env:
  REGISTRY_IMAGE: indexyz/alpine-desktop

jobs:
  lint:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Login to Docker registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: ${{ env.REGISTRY }}

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ${{ env.REGISTRY_IMAGE }}
        docker push ${{ env.REGISTRY_IMAGE }}
